// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateSampleInput struct {
	Name string `json:"name"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateSampleInput struct {
	Name string `json:"name"`
}
