import type { Metadata } from "next";
import Link from 'next/link';
import Image from 'next/image';
import "@/styles/globals.css";

import React from 'react';

import { Providers } from './providers'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className="h-full overflow-hidden">
      <body className="flex flex-col min-h-screen">
        <Providers>
          <header className="flex-shrink-0 fixed top-0 left-0 right-0 z-10">
            <nav className="bg-gray-800 w-screen">
              <div className="flex items-center pl-8 h-14">
                <div className="flex space-x-4">
                  <Link href="/" className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded">Home</Link>
                  <Link href="/type-script" className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded">TypeScript</Link>
                  <Link href="/blog-page" className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded">Blog</Link>
                  <Link href="/contact-page" className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded">Contact</Link>
                  <Link href="/modal-page" className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded">Modal</Link>
                  <Link href="/reducer-page" className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded">Reducer</Link>
                  <Link href="/redux-page" className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded">Redux</Link>
                  <Link href="/api" className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded">API</Link>
                  <Link href="/graphql" className="text-gray-300 hover:bg-gray-700 px-3 py-2 rounded">Graphql</Link>
                </div>
              </div>
            </nav>
          </header>
          <main className="flex-1 w-full mt-14 mb-12 overflow-y-auto">
            {children}
          </main>
          <footer className="flex-shrink-0 fixed bottom-0 left-0 right-0 h-12 flex justify-center items-center border-t bg-white">
            <a className="flex items-center">
            Copyright©
              <Image src="/sanuna.svg" alt="Vercel Logo" width={25} height={25} className="mx-1"/>
            All Rights Reserved
            </a>
          </footer>
        </Providers>
      </body>
    </html>
  );
}
